### PR TITLE
Update sugargame to v1.2

### LINKED ISSUE #10: Port to latest Sugargame
https://github.com/sugarlabs/sugargame

### PR DESCRIPTION
**Pull request by nswarup14**
Fixes #10 
**Updates**
1) Update sugargame directory to v1.2

Tested on: Ubuntu 18.04 Sugar v0.112

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.  Please review changes in 0b9f43c and 5615bbd and give your consent or comments.  There remains an issue; the progress bar has shifted down; before your changes it looked like this;

screenshot_ubb_2019-01-18_09 07 29

but after your changes like this;

screenshot_ubb_2019-01-18_08 53 07

Looking at your changes, there was nothing obvious about repositioning.  Please debug the problem, explain the cause, and push a fix, thanks.

* [ ] restore progress bar position to normal.

**Comment by nswarup14** [comment]
New commits reviewed.
I shall look into the issue of fixing the progress and push a fix soon.

**Comment by quozl** [comment]
Thanks.  I seem to remember something in Sugargame v1.1 to v1.2 that might cause it, but haven't put my finger on it yet.  Let us know what you find.

**Comment by nswarup14** [comment]
@quozl 
I am unable to figure out what's causing the progress bar to fall down. I extracted the location of the loaded `frame2.png` in both my branch as well as master and its the same. Nothing else has been changed in the codebase.

**Comment by quozl** [comment]
@nswarup14, I've tested both branches with a temporary patch to print location of `frame2` and display size.  The cause is different display size;
* _master_, (1024, 715)
* _port_sugargame_, (1024, 768)

So this looks to be a mistake in Sugargame, which as you can see changed the method to determine the display size.  Can you suggest a way to fix it?

Here's the temporary patch;

```diff
diff --git a/g.py b/g.py
index 5b31972..9447f95 100755
--- a/g.py
+++ b/g.py
@@ -31,6 +31,7 @@ def init(): # called by run()
     screen.fill((128,0,0))
     pygame.display.flip()
     w,h=screen.get_size()
+    print "screen size (%r, %r)" % (w, h)
     if float(w)/float(h)>1.5: #widescreen
         offset=(w-4*h/3)/2 # we assume 4:3 - centre on widescreen
     else:
diff --git a/iq1.py b/iq1.py
index 6804b1d..5931c69 100755
--- a/iq1.py
+++ b/iq1.py
@@ -66,6 +66,7 @@ def setup():
 def draw():
     x,y=tns[0].xy; dx=g.sy(.5); dy=g.sy(.45)
     x-=dx; y-=dy; g.screen.blit(g.frame2,(x,y))
+    print "blit frame2 at (%r, %r)" % (x, y)
     n=g.solved+1
     if n==11: n=10
     for ind in range(n):
```

**Comment by rhl-bthr** [comment]
Stale. Closing

**Pull request closed without merging**
